### ISSUE TITLE
Question: why http methods are restricted?

### ISSUE THREAD

**Issue by alekitto** [OAI/OpenAPI-Specification#2020] opened 2019-10-01 10:36 UTC
Stating that [RFC 7231 Section 4.1](https://tools.ietf.org/html/rfc7231#section-4.1) does not limit HTTP method and defines it as

```
    method = token
```

what are the reasons of restricting the available http methods in this specification?

Other issues are present requesting to support other methods (for example REPORT #658, SEARCH #1306, LINK and UNLINK #480 or others #1747).
Is it not easier (and more coherent to the HTTP spec) to allow every method, standardizing the behavior of only some of these but allowing the usages of every method, even the custom ones?

**Comment by MikeRalphson** [comment] 2019-11-26 13:14
Duplicate of #1747

**Closed by MikeRalphson** 2019-11-26 13:14 UTC
