### ISSUE TITLE
Make operationId mandatory

### ISSUE THREAD

**Issue by slinkydeveloper** [OAI/OpenAPI-Specification#1907] opened 2019-04-26 07:06 UTC
Hi,
I would like to propose to make `operationId` required in Operation definition. As the specification states, this field may be used in tooling to uniquely identify operations. I have a couple of real world examples:

* different tools that support both http method/path combination have an algorithm that transforms the http method/path combination to an operationId, giving sometimes awful/unexpected results. For example, let's say that you have a contract without operationIds and you generate clients for it using any tool. One day you update the contract changing a path name or a path parameter name. The generated clients will durely change the method names, while the meaning of the operation is always the same! 
* Some libraries (like mine https://vertx.io/docs/vertx-web-api-contract/java/) uniquely refer to an operation using the operationId more than the http method/path combination. While the http method/path combination is subject to changes, while `operationId` usually remains related with the meaning of the operation.

In the end, I personally see `operationId` as the only meaningful operation identifier, that's why I think we should encourage users to define it, making it mandatory

WDYT?

**Comment by ahl** [comment] 2019-04-26 18:47
Strong agreement from me. Our use of OperationId requires this for unique naming, through I can see how code or doc generation would not require it.

**Comment by nfroidure** [comment] 2019-04-30 13:34
First time I had an error for a lacking / duplicated `operationId`, it took time for me to handle the fact that the schema validator weren't warning me on this.

Would be nice if anyone could explain a case where it would be useful to not do this since I cannot imagine any in fact.

**Comment by MikeRalphson** [comment] 2019-04-30 13:49
This issue is a dupe of closed issue #1019 (though that issue was closed by it's original poster).

To summarise, the arguments against making `operationId` mandatory are:
* it would make document authoring more tedious and error-prone and probably increase the number of non-compliant documents in the wild
* making this property mandatory would likely not result in **quality** `operationId`s being used
* it is trivial to generate a missing `operationId` from the method and path, though perhaps not as readable
* if the method or path changes, is it really the same operation?
* alternative approaches such as using a `uuid` can be used where not intended for human consumption
* where necessary, document authors are likely to be already including this information
* this would be a breaking change and thus could not be considered until the OAS 4.x timeframe

This really leaves the case where a document author has not included `operationId`s but a third party requires them for a use-case such as code generation or framework ingestion. The proposed overlay approach in OAS 3.1 would likely be a reasonable way of resolving this issue.

> First time I had an error for a lacking / duplicated operationId, it took time for me to handle the fact that the schema validator weren't warning me on this.

A good OAS validator should definitely report an error on a duplicated `operationId` and several linters which use rules originated in `oas-kit` warn about missing `operationIds` by default.

**Comment by mkistler** [comment] 2019-05-02 11:26
I think the issue of missing operationIds is best solved by a good linting tool. Our tooling also requires operationIds but we use a linter to detect when they are missing.

@MikeRalphson mentions `oas-kit` above. There are many more available:

https://nordicapis.com/8-openapi-linters/

**Comment by PureKrome** [comment] 2020-03-15 22:28
For some context, how is an `OperationId` used? What is it's purpose? 

Is this used by SDK's? So if I generate a Typescript SDK of the common Petstore OpenAPI schema, then in my typescript code, to 'call' these OpenAPI endpoints, I would be calling the `OperationId`? 

REF: also [asked by me here](https://stackoverflow.com/questions/60681379/how-is-the-operationid-used-from-an-openapi-schema?noredirect=1#comment107382607_60681379).

**Comment by handrews** [comment] 2024-01-27 02:47
This seems like it was solidly rejected in favor of validators/linters, so I'm going to close it as resolved.  @PureKrome , I'd recommend asking your questio on the OpenAPI Slack, which you can get to under the "Participate" menu on the OpenAPI web site.

**Closed by handrews** 2024-01-27 02:47 UTC
