### ISSUE TITLE
clarification about required with readOnly and writeOnly

### ISSUE THREAD

**Issue by dario-frongillo** [OAI/OpenAPI-Specification#2110] opened 2020-01-19 10:57 UTC
Hi All,
i need a confirmation that i understood correctly the behavior of required with readonly and writeonly.

- required field X without  readonly and writeonly: the field X is mandatory in request and response
- field X required and readOnly: the field x is mandatory in response but not in request
- field X required and writeOnly: the field x is mandatory in request but non in response

as i wrote is correct ?

**Comment by tedepstein** [comment] 2020-01-19 20:51
@dario-frongillo , What you wrote is mostly correct, but the [language in the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#user-content-schemareadonly) is a little stronger with regard to `readOnly` and `writeOnly`. 

I think your summary would be more precise with the following changes:

> * required field X without  readonly and writeonly: the field X is mandatory in request and response
> * field X required and readOnly: the field x is mandatory in response but ~not in request~ **SHOULD NOT be included in the request.**
> * field X required and writeOnly: the field x is mandatory in request but ~not in response~ **SHOULD NOT be included in the response.**

**Comment by GuillaumeUnice** [comment] 2020-01-20 11:21
Hi, is that possible to confirm the following table.
Cause I've like the feeling there is some ambiguous think behing that:

|              | Read Only Get | Read Only Post   | Write Only Get | Write Only POST  | Nothing Get | Nothing Post |
|--------------|---------------|------------------|----------------|------------------|-------------|--------------|
|              | Req->Res      | Req->Res         | Req->Res       | Req->Res         | Req->Res    | Req->Res     |
| Required     | ∅->Must       | Should Not->Must | ∅->Should not  | Must->Should not | ∅->Must     | Must->Must   |
| Not required | ∅->May        | Should Not->May  | ∅->Should not  | May->Should not  | ∅->May      | May->May     |

My goal behind consist to use as more possible the same schema for one resource and just fine-tune the Wo, Ro and required flag

**Comment by handrews** [comment] 2020-02-09 07:26
@GuillaumeUnice I'm fairly sure that table matches @tedepstein 's comment, and from a JSON Schema perspective, it also looks good.  Our wording is more lax, and assumes that in some cases, particularly a GET->modify->PUT cycle, it makes sense to allow but ignore read-only fields on the PUT.  It sounds like PUT isn't relevant to you, though.  If you're using POST to create, though, I agree with the SHOULD NOT.

**Comment by tedepstein** [comment] 2020-02-16 18:30
@dario-frongillo, it looks to me like this issue is resolved, so I'll close it for now. If you feel the issue isn't really resolved, please feel free to reopen the issue and provide further comments.

**Closed by tedepstein** 2020-02-16 18:30 UTC
Labels: question, schema-object
