### ISSUE TITLE
Allow repetition of operationId

### ISSUE THREAD

**Issue by falk-stefan** [OAI/OpenAPI-Specification#3223] opened 2023-03-31 10:33 UTC
Whenever I am using OpenAPI, I'll always get across this issue that the `operationId` has to be globally unique and that it, somehow, is also the basis for naming functions.

So, it's impossible to have something like this (Java, Spring Boot)

```java
@RestController
public class SomethingController {
    @RequestMapping(value = "/something", method = RequestMethod.GET)
    public SomethingDto get() {
        return new SomethingDto();
    }
}

@RestController
public class OtherthingController {
    @RequestMapping(value = "/otherthing", method = RequestMethod.GET)
    public OtherthingDto get() {
        return new OtherthingDto();
    }
}
```

without getting enumerated function names as a result (e.g. typescript-angular generator):

```typescript
SomethingControllerService  #get
OtherthingControllerService #get1
                                ^
```

It makes me wonder how and why this decision has been made and even more so, that this is still the case in v3. 

If there is the need for a unique identifier, `operationId`, why isn't there simply a non-unique peroperty `operationName` which is allowd to be repeated? 

The result is that we have to rewrite function names which ends up looking like this:

```typescript
somethingController.getSomething(/* .. */);
somethingController.createSomething(/* .. */);
somethingController.updateSomething(/* .. */);
somethingController.deleteSomething(/* .. */);
somethingController.getAllSomething(/* .. */);
```

instead of just

```typescript
somethingController.get(/* .. */);
somethingController.create(/* .. */);
somethingController.update(/* .. */);
somethingController.delete(/* .. */);
somethingController.getAll(/* .. */);
```

I'm just raising this because I feel like this is an unnecessary complication when it comes to generating code and using it with a client.

### See also

- https://github.com/go-swagger/go-swagger/issues/1143

**Comment by rafalkrupinski** [comment] 2024-01-01 16:30
I think it would make more sense to have `resourceName` in `Path item object`. It would work for any RESTful service, which by definition assigns paths to resources.

Note that sometimes resources are nested (`/resource/subresource`).

**Comment by handrews** [comment] 2024-01-27 20:25
This is a problem with Spring Boot using `operationId` in a way that was not intended.  The purpose of `operationId` is to be a unique identifier across the whole API, and other parts of the specification depend on this.

**Comment by handrews** [comment] 2024-01-28 17:49
Actually, I can't tell whether the problem is with Spring Booth or Typescript Angular Generator.

If Spring Boot is insiting on creating things like `get1`, `get2`, etc. as `operationId`s _and_ won't let you set override them with something meaningful, that's a problem with Spring Boot and should be raised there.

If Spring Boot is _not_ doing that, and Typescript Angular Generator is coming up with `get1` etc on its own (and there's no way to change it), the problem is with Typescript Angular Generator and should be raised there.

As far as the spec is concerned, `operationId` is doing what it's intended to do, and really cannot be made non-unique without breaking tons of other things.

Since @rafalkrupinski asked about a new non-unique field to do this, I'm going to add to the title to reflect that so I don't keep coming here intending to close it :-)

**Comment by handrews** [comment] 2024-01-28 17:52
@rafalkrupinski actually I realize I misread your question and it is about resource identification.  Could you file that as a new issue?  I think it is likely to get addressed in OAS 4 Moonwalk (see OAI/sig-moonwalk#30), but if you want it considered for 3.x it should get its own issue here.  I suspect it's too big of change for 3.x, but it's possible it could be accommodated.

**Closed** 2024-01-28 17:53 UTC

**Comment by rupert-jung-mw** [comment] 2024-11-07 10:33
Having the very same problem. I have unified names for CRUD methods in all REST controllers and now they are all postfixed with numbers.

**Comment by falk-stefan** [comment] 2025-04-06 10:22
@handrews I just noticed the issue was closed as "not planned" but you linked a discussion which might address the issue for OAS v4 - do you know if that'll actually happen?
