### ISSUE TITLE
Minor typo in example docs

### ISSUE THREAD

**Issue by b2397** [OAI/OpenAPI-Specification#2172] opened 2020-03-06 19:48 UTC
https://github.com/OAI/OpenAPI-Specification/blob/e42b09013b1ec4093144fde05afe14ff8b4b0c48/examples/v3.0/petstore-expanded.yaml#L83

...should probably be something like...

```yaml
operationId: findPetById
```

**Comment by MikeRalphson** [comment] 2020-03-06 19:52
Closing as dupe of #1988

**Closed** 2020-03-06 19:53 UTC
