### ISSUE TITLE
OpenAPI 3.1 examples not validating through AJV using OpenAPI 3.1 spec

### ISSUE THREAD

**Issue by essential-randomness** [OAI/OpenAPI-Specification#2689] opened 2021-08-31 22:42 UTC
Hello,
there is a lot of JavaScript tooling that uses [AJV](https://github.com/ajv-validator/ajv/) to validate OpenAPI specs. None of it seems to support 3.1, which is really unfortunate. I was trying to remedy the situation, but failed miserably.

As far as I can tell (see https://github.com/ajv-validator/ajv/issues/1745) even the examples in your OpenAPI3.1 folder do not pass validation. The AJV folks (understandably) won't help unless I create a minimal reproducible example of a failing schema, which I'm not really qualified to do. 

Would you be able to help/shed light on what's going on?

Copying the relevant details:
----
**Ajv options object**
```
{
    allErrors: true, 
    validateFormats: false, 
    strictSchema: false, 
    strictTypes: false
}
```
See OAI/OpenAPI-Specification#2489 for a discussion on the options.

**JSON Schema**

The OpenAPI 3.1 schema defined here: https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.1/schema.json

**Sample data**

the OpenApi v3.1 webhook example here: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.1/webhook-example.json

**Your code**

See: https://runkit.com/essential-randomness/612d87df07ae0a00092a3492.

This simply call ajv with the given options, passes the OpenApiv3.1 schema and tries to validate the OpenApi Webhook example.

**Validation result, data AFTER validation, error messages**

Error message:
```
Invalid: 
data/webhooks/newPet/post/requestBody/content/application~1json/schema must NOT have unevaluated properties, 
data/webhooks/newPet/post/requestBody must match "else" schema,
data/webhooks/newPet must match "else" schema, 
data/components/schemas/Pet must NOT have unevaluated properties, 
data/components/schemas/Pet must NOT have unevaluated properties

```
----

Thank you!  Hopefully the errors are more understandable if you can read schemas :)

**Comment by jdesrosiers** [comment] 2021-09-01 18:42
This is a bug in ajv related to `$dynamicRef`. Here's your minimal reproduction.

**schema**
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "type": "object",
  "properties": {
    "schema": { "$dynamicRef": "#meta" }
  },
  "unevaluatedProperties": false,

  "$defs": {
    "schema": {
      "$dynamicAnchor": "meta",
      "type": ["object", "boolean"]
    }
  }
}
```

**instance**
```json
{
  "schema": { "type": "string" }
}
```

It appears that the `$dynamicRef` is resolving to the root of the schema rather than `/$defs/schema` where the `$dynamicAnchor` is located.

**Comment by essential-randomness** [comment] 2021-09-01 18:51
Thank you so much for you help! Will follow up with them and hopefully we can get 3.1 working :)

**Comment by karenetheridge** [comment] 2021-09-16 19:49
@essential-randomness can you cross-link the ajv ticket here so others can follow its progress?

**Comment by essential-randomness** [comment] 2021-09-17 02:01
Absolutely! Here it is

https://github.com/ajv-validator/ajv/issues/1745

**Comment by no-identd** [comment] 2021-11-08 10:21
See also https://github.com/ajv-validator/ajv/issues/1573 by @seriousme. @epoberezkin originally closed https://github.com/ajv-validator/ajv/issues/1745 as a duplicate of that one, but 8 days later reopened it

**Comment by seriousme** [comment] 2021-11-08 17:20
@essential-randomness : see also: https://github.com/seriousme/openapi-schema-validator ;-)

**Comment by essential-randomness** [comment] 2021-11-08 17:28
> @essential-randomness : see also: https://github.com/seriousme/openapi-schema-validator ;-)

Oh I use this! (Thanks for making it)

Fairly sure it doesn't catch everything though. I've had to use 2-3 different validators to get most of the errors out and even then stuff still slips through. I've also not been able to make 3.1 schemas pass for other JS libraries, and when I looked at why yours worked there was a reason for why yours would and theirs wouldn't that I have now forgotten.

**Comment by jdesrosiers** [comment] 2021-11-08 20:50
I see that `@seriousme/openapi-schema-validator` modifies the official meta-schemas to work around the ajv bug.

[@hyperjump/oas-schema-validator](https://github.com/hyperjump-io/oas-schema-validator) works properly without workarounds and can validate the schemas against the OpenAPI JSON Schema vocabulary or whatever JSON Schema dialect you choose. Here's a quick example.

```
const OasSchema = require("@hyperjump/oas-schema-validator");
const oas31 = require("./oas31.schema.json");
const oas31base = require("./oas31base.schema.json");
const example = require("./example.openapi.json");

(async function () {
  OasSchema.add(oas31, "https://spec.openapis.org/oas/3.1/schema");
  OasSchema.add(oas31base, "https://spec.openapis.org/oas/3.1/schema-base");

  const schema = await OasSchema.get("https://spec.openapis.org/oas/3.1/schema-base");
  const validate = await OasSchema.validate(schema);

  const result = validate(example, OasSchema.BASIC);
  console.log(result);
}()); 
```

**Comment by epoberezkin** [comment] 2021-11-11 12:25
Yes, working on a fix here too… It’s a tricky one, at the time it was implemented the spec didn’t settle yet, but should be ok soon.

**Comment by seriousme** [comment] 2022-03-22 18:10
Just tested, [openapi-schema-validator](https://github.com/seriousme/openapi-schema-validator) validation failed at the raw spec containing the `"$dynamicRef": "#meta"` hence it still uses a modified 3.1 schema where `"$dynamicRef": "#meta"` has been converted to `"$ref": "#/$defs/schema"`

With the modified 3.1 schema validation tests succeed as before.

**Comment by no-identd** [comment] 2022-09-09 20:25
@seriousme @MatanYemini try https://github.com/cdimascio/express-openapi-validator/pull/713#issuecomment-1140492669 ?

**Comment by jdesrosiers** [comment] 2022-09-10 18:18
@no-identd Upgrading AJV won't fix this problem until AJV fixes the [bug](https://github.com/ajv-validator/ajv/issues/1745) responsible for the problem.

**Comment by handrews** [comment] 2024-01-27 21:09
Since the only problems here are with JSON Schema validators, and not the OAS itself, I'm going to close this- there are plenty of issues tracking the validator bugs/missing features.

**Closed by handrews** 2024-01-27 21:09 UTC
