### ISSUE TITLE
Require property based on another property value

### ISSUE THREAD

**Issue by tmdoit** [OAI/OpenAPI-Specification#1490] opened 2018-02-15 08:15 UTC
I have the following scheme:
```yaml
    Issue:
      type: "object"
      properties:
        data:
          type: "object"
          properties:
            type:
              type: "string"
              example: "issue"
            attributes:
              type: "object"
              properties:
                altAddress:
                  type: "boolean"
                  example: false
                altAddressCustomerName:
                  type: "string"
                  minLength: 3
                  maxLength: 200     
                altAddressStreet:
                  type: "string"
                  minLength: 3
                  maxLength: 100       
                altAddressPostalCode:
                  type: "integer"
                  format: "int32"
                  minLength: 5
                  maxLength: 5
                altAddressCity:
                  type: "string"
                  minLength: 3
                  maxLength: 30     
```
I want to altAddress... properties to be required if altAddress property is set to true. How can I achieve this?

**Comment by MikeRalphson** [comment] 2018-02-15 09:01
Duplicate of #1321

**Comment by webron** [comment] 2018-02-15 18:54
Closing as duplicate.

**Closed by webron** 2018-02-15 18:54 UTC
