### ISSUE TITLE
Add version field to Operation object

### ISSUE THREAD

**Issue by DanielYWoo** [OAI/OpenAPI-Specification#2406] opened 2020-11-12 11:21 UTC
We already have API versioning for the whole APIs, that's good, but sometimes we also need versioning on each API Operation. From the doc: https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#operationObject I cannot find a version per Operation. Currently I can hack that with tags, but I hope we can have a dedicated optional version field in Operation.

Then in java annotation, I can do something like this
```
    @Operation(summary = "Get a list of activities", version="123" )
```

And in the the API spec, I can specify multiple versions for a single operation like this (a list of operations with different versions)
```
get:
- summary: Find pets by ID
  operationId: getPetsById
  version: "121",
  responses:
    '200': ...
- summary: Find pets by ID
  operationId: getPetsById
  version: "123",
  responses:
    '200': ...
```
or I can also just specify the latest version (compatible with the current spec, a single operation instead of a list of operations)
```
get:
  summary: Find pets by ID
  operationId: getPetsById
  version: "123",
  responses:
    '200': ...
```

**Comment by MikeRalphson** [comment] 2020-11-12 11:49
Duplicate of #2142 please continue the conversation on that issue, thanks.

**Closed by MikeRalphson** 2020-11-12 11:49 UTC
