### ISSUE TITLE
3.1 schema for top-level `servers` field does not match spec

### ISSUE THREAD

**Issue by lmmarsano** [OAI/OpenAPI-Specification#2531] opened 2021-04-09 20:26 UTC
The schema says the value for `servers` is a single server object.
https://github.com/OAI/OpenAPI-Specification/blob/6e5b27a191c1cba9b3f61e7bf9b031fa75a0157f/schemas/v3.1/schema.yaml#L14-L15
[The spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#openapi-object) says it's an array of those objects.

servers | [Server Object] | An array of Server Objects, which provide connectivity information to a target server. If the servers property is not provided, or is an empty array, the default value would be a Server Object with a url value of /.
-- | -- | --

**Comment by jdesrosiers** [comment] 2021-04-09 20:55
Duplicate of https://github.com/OAI/OpenAPI-Specification/pull/2526

**Closed** 2021-04-09 21:24 UTC
