### ISSUE TITLE
Image for OpenAPI button

### ISSUE THREAD

**Issue by RomanHotsiy** [OAI/OpenAPI-Specification#614] opened 2016-03-30 22:38 UTC
I'd like to add a button "Download OpenAPI" for API console I am working on (https://github.com/Rebilly/ReDoc/issues/1). Before renaming to OpenAPI you had Swagger logo:
![previous logo](http://2434zd29misd3e4a4f1e73ki.wpengine.netdna-cdn.com/wp-content/uploads/2016/02/swagger-logo.png)
But your current logo is vertical and can't be placed nicely on a button
![](https://avatars3.githubusercontent.com/u/16343502?v=3&s=200)

Is the old logo still actual? If not, can you provide a version of the logo that can be used for buttons?
I think this problem is not limited to my project because similar buttons are becoming an increasingly popular trend, for example, "Postman Button". It would be even better if you can host officially .svg image for such buttons.

**Comment by earth2marsh** [comment] 2016-03-31 15:52
Thanks for the suggestion, @RomanGotsiy. Logo treatment is a high priority for the OAI marketing group, and once an iconified version is ready, we'll add an SVG version in a (forthcoming) style guide.

**Comment by RomanGotsiy** [comment] 2016-03-31 16:11
Thanks, looking forward to seeing it!

**Comment by RomanGotsiy** [comment] 2016-06-24 12:33
@earth2marsh I've noticed you have a new logo.
Could you please upload svg to this repository?

**Comment by RomanGotsiy** [comment] 2016-07-20 20:49
@earth2marsh any updates on this?

**Comment by earth2marsh** [comment] 2016-07-21 23:55
The logo represents the organization and the specification. A style-guide was in the works, but I'm not sure it's been released—let me check and get back to you.

**Comment by mittsh** [comment] 2016-07-22 09:55
@earth2marsh we're very much interested in an SVG logo for OAI at [Paw](https://luckymarmot.com/paw) 😄 any update would be very welcome!

**Comment by mittsh** [comment] 2016-07-22 10:41
Well we needed that quickly, so I went ahead and reproduced the OAI logo with Sketch. Here's the SVG file: https://cl.ly/130O173n2c2d
And the gray version: https://cl.ly/1K1q0Y3Z0G0c

It looks like this:

![image](https://cloud.githubusercontent.com/assets/1319906/17054819/7fbaa296-5009-11e6-9d89-b8e288afb0fa.png)

![image](https://cloud.githubusercontent.com/assets/1319906/17054822/833ad44a-5009-11e6-8fcb-fd536d15ecf9.png)

**Comment by earth2marsh** [comment] 2016-08-24 19:50
Vector and bitmap versions of the OAI logo are now available here: https://github.com/OAI/OpenAPI-Style-Guide/tree/master/graphics

**Comment by dimus** [comment] 2020-12-06 13:37
I would like my README to have an OpenAPI badge/button (similar to test coverage, docs badge, etc)  that points to a swaggerhub URL. Is there such a thing?

**Comment by MikeRalphson** [comment] 2020-12-06 14:03
You can get a shields.io badge, or one from here: https://mermade.org.uk/openapi-converter though that doesn't have the logo.

**Comment by dimus** [comment] 2020-12-06 15:43
Thank you!

**Comment by ncaidin** [comment] 2021-04-12 11:28
@MikeRalphson , what action are you wanting me to take on this issue? 
Thanks.

**Comment by MikeRalphson** [comment] 2021-04-12 11:35
It was previously assigned to Jeff. You might want to provide logos with transparent backgrounds. Or not.

**Closed** 2021-04-14 14:33 UTC

**Comment by ncaidin** [comment] 2021-04-14 14:35
Hi all, If anyone needs anything that is not provided by the OpenAPI style guide, https://github.com/OAI/OpenAPI-Style-Guide , please let me know. Depending on the request, there is a good chance I would take it to be reviewed by the OpenAPI Marketing group to decide how to respond. Thanks for reporting.
