### ISSUE TITLE
HTCPCP methods not supported

### ISSUE THREAD

**Issue by prostetnicvogonjeltz** [OAI/OpenAPI-Specification#2059] opened 2019-11-19 17:57 UTC
We found out that we were unable to complete our specification due to missing support of the methods specified in the RFC 2324 (https://tools.ietf.org/html/rfc2324) standard.

In detail, the BREW, WHEN and PROPFIND seem to be unsupported by OpenAPI version 3.0, even though they are included and even required by the RFC 2324 standard.

**Comment by MikeRalphson** [comment] 2019-11-26 13:13
Duplicate of #1747

**Closed by MikeRalphson** 2019-11-26 13:13 UTC
