### ISSUE TITLE
introduction to the @Since documentation tag 

### ISSUE THREAD

**Issue by LasneF** [OAI/OpenAPI-Specification#2444] opened 2021-01-14 13:57 UTC
Given a OAS spec i want to know for each field when it has been introduced 

for instance my OAS spec is 1.2.3 
but some end point where introduce in 1.2.0 

this should be done at most of the level of the spec 
end points 
verbs
field 

this would allow a caller to minimize the surface 

you have same concept on the Javadoc for instance

**Comment by hkosova** [comment] 2021-01-14 15:12
Duplicate of #833

**Closed** 2021-01-14 15:29 UTC
