### ISSUE TITLE
White background in logo in readme in dark mode

### ISSUE THREAD

**Issue by mwomick** [OAI/OpenAPI-Specification#2522] opened 2021-04-06 17:37 UTC
[Cosmetic] Change to transparent background for compatibility with dark mode

**Comment by MikeRalphson** [comment] 2021-04-06 18:28
Thanks for reporting this. PRs welcome.

**Comment by Shiva9801** [comment] 2023-09-13 07:48
Hello @MikeRalphson  , I could resolve this issue . Can you make me Assignees?

**Comment by Shiva9801** [comment] 2023-09-13 07:50
We can change to a transparent background for the image.
I'm facing an issue i.e. the image is attached via URL and I can't make changes to it; so for trial purposes, I downloaded and edited the image and got a URL from a website and the issue seems to be resolved in dark mode.

**Comment by LasneF** [comment] 2024-03-21 10:27
@MikeRalphson , @handrews  given the PR has been merged , looks we can close the issue isn't it ?

**Comment by handrews** [comment] 2024-04-26 00:14
@LasneF yup, not sure how I missed your comment earlier.  Closing as complete!

**Closed by handrews** 2024-04-26 00:14 UTC
Labels: help wanted
