### ISSUE TITLE
Open TSC Meeting - November, 14th 2019

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#2052] opened 2019-11-07 16:59 UTC
**NOTE: This meeting is on Thursday at 9am - 10am PT**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting*

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  

/cc @OAI/tdc Please suggest items for inclusion

**Comment by tedepstein** [comment] 2019-11-12 15:44
Suggested agenda item, discussed with @darrelmiller and @webron on Slack:

## Expedited merging of new and changed proposals

When we introduced proposals, we agreed in principle that new proposals and changes to proposals (by the proposal submitter) should be expedited, not held up in the general PR backlog.
But we never put a process in place to ensure that this happens.  As it stands, the GitHub PR process gets in the way of the proposals process.

We discussed two possible solutions: 

# We define a policy that any TSC member can merge a proposal/proposal change made by the proposal owner without a second sign-off and give proposal writers permission to harass on the social media platform of their choice.
# Proposals could go into another repo with a broader list of committers. Like maybe submitting a proposal gets you promoted to committer status in that repo, and we clean up the committer list from time to time.

Let's discuss and agree on a way forward.

**Comment by darrelmiller** [comment] 2019-11-14 16:31
I will be available to start the meeting but I can't stay in the call unfortunately.

**Comment by tedepstein** [comment] 2019-11-14 17:31
Meeting minutes: 

* On the topic of _expedited merging of new and changed proposals_:<br/><br/>
    * The consensus was in favor of having a separate repo for proposals. To clarify, this would be a dedicated repository, _only_ for proposals. It would not be a fork or a duplicate of this OpenAPI-Specification repo. We would link to the proposals repo from the OpenAPI-Specification readme, from the OpenAPIs.org website, and from elsewhere as needed.<br/><br/>
    * @webron mentioned on a Slack chat that he thinks [GitHub Actions](https://github.com/features/actions) might be able to automate the merging of PRs containing new proposals or changes to proposals. If this progresses to a working POC, we'd like to see it before we create the new repo. @webron might need someone with JavaScript chops to help prototype this. Any volunteers?<br/><br/>
* @namdeirf Noted that the TSC calendar should be updated to reflect the limited number of Thursdays left in 2019. TSC calls falling on Thanksgiving or other holiday weeks should be removed from the calendar.  I'm not sure who owns this calendar, so if someone knows, please pass it on.

**Comment by handrews** [comment] 2020-02-11 00:50
@darrelmiller does this info need to be actively retained?  If so can we put it in its own issue or something and close out the meeting issue?

**Comment by darrelmiller** [comment] 2020-02-11 01:09
LOL, apparently I didn't read the consensus of the meeting and I created proposals in the same site!  Oops.  Sure we can close this.

**Closed by darrelmiller** 2020-02-11 01:09 UTC
Labels: Housekeeping
