### ISSUE TITLE
OpenAPI 3.0 Links

### ISSUE THREAD

**Issue by mitrey** [OAI/OpenAPI-Specification#1495] opened 2018-02-28 12:16 UTC
OpenAPI 3.0 introduced a new feature - links:
https://swagger.io/docs/specification/links/

How can I use it for response with an array of items?

Example:

![image](https://user-images.githubusercontent.com/7721982/36787267-3436c76c-1c92-11e8-9ade-d421490dc10f.png)

Thank you in advance!

**Comment by MikeRalphson** [comment] 2018-02-28 15:13
Hi @mitrey - it looks like this is a duplicate of #1327 - if so, please join the conversation there.

If I've misunderstood your issue, please chase and we can re-open this one. Thanks.

**Closed by MikeRalphson** 2018-02-28 15:13 UTC
