### ISSUE TITLE
Issue - XML representation of response payload and request body

### ISSUE THREAD

**Issue by hrennau** [OAI/OpenAPI-Specification#2097] opened 2020-01-10 13:02 UTC
In the OpenAPI spec, section "XML Object",
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#xmlObject

implicitly defines default rules for the XML representation of JSON properties:

- an object property is represented by an XML element with a name equal property name
- an array value is represented by repeated XML elements, one for each array item, without wrapper element

The spec does not make statements about how XML elements representing a JSON root value (the value representing the response payload, or the request body) should be represented:
- choice of element name
- handling of a JSON root value which is an array 

Note: a JSON array as root value obviously requires a wrapper XML element containing the item XML elements; so there are two element names to choose.

PROPOSAL
(1) Section "Schema object", table "Fixed Fields", row "xml":

The constraint 
_"This MAY be used only on properties schemas. It has no effect on root schemas. "_
is modified so that XML objects **CAN** be used for root schemas defining request bodies and response payloads. These schemas can be found at the following (informal) JSON paths:
Response payload:
/paths/{path}/(get|post|put|delete|options|head|patch)/responses/({return-code}|default)/content/{mediatype}/schema
Request body:
/paths/{path}/(get|post|put|delete)/requestBody/content/{mediatype}/schema

(2) The spec includes a text defining default rules for the XML representation of response payloads and request bodies.

**Comment by handrews** [comment] 2024-04-28 18:28
Closing as duplicate of #1435

**Closed by handrews** 2024-04-28 18:28 UTC
Labels: schema-object, xml, media and encoding
