### ISSUE TITLE
Support for Server Side Events

### ISSUE THREAD

**Issue by vipinvkmenon** [OAI/OpenAPI-Specification#1499] opened 2018-03-02 10:01 UTC
There should be support to represent Server Side event streams in OAS 3.

**Comment by MikeRalphson** [comment] 2018-03-28 07:20
@vipinvkmenon is this issue a duplicate of #396 ?

**Comment by gtskaushik** [comment] 2018-06-26 08:21
I hope this is a duplicate of #396 . But this is a feature in need

**Closed** 2020-11-03 10:58 UTC
