### ISSUE TITLE
allOf in paths to split paths into multiple files

### ISSUE THREAD

**Issue by Giri-oss** [OAI/OpenAPI-Specification#769] opened 2016-08-25 05:36 UTC
from 2.0 specification i can see "allOf"is applicable for only schema object, is there any specific reason for that restriction. this would be very helpful feature to split "paths" into multiple files.

i understand that it can be done today by defining path item object in different files but i am looking at keeping path and path item object in separate files. one consolidated file where i can include all paths using "allOf" and create one API document.

{
  "swagger": "2.0",
  "info": {
    "version": "1.0.1",
    "title": "Test API",
    "description": "Test API description"
  },
  "paths": {
    "allOf": [
      {
        "$ref": "API/ResGroup1.json#/rg1_rs1"
      },
      {
        "$ref": "API/ResGroup1.json#/rg1_rs2"
      },
      {
        "$ref": "API/ResGroup2.json#/rs1"
      }
    ]
  }
}

my questions are
"allOf" in paths object is it a feature that is been considered for future releases?
 is there any effort already in progress to support "allOf" in paths object?

**Comment by webron** [comment] 2016-08-25 06:26
I see no reason to support `allOf` anywhere outside the Schema Object. `allOf` is a JSON Schema construct. The spec is not a JSON Schema. We may want to provide support for the use case, but the usage of `allOf` is needlessly verbose.

**Comment by BabuGiri** [comment] 2016-08-25 08:02
i understand now why "allOf" is supported only in Schema Object. approach in above is an example to express use case, i am interested in if there is already some work to support above use-case.

Thank you

**Comment by BiteBit** [comment] 2017-06-13 15:30
So is there any other solutions to split paths into multiple files?

**Comment by francescobianco** [comment] 2018-08-26 00:28
@BabuGiri @webron I suggest to build file using command line toolkit that links multiple YAML files with $include tag. Look this https://github.com/javanile/yamlinc add-in project task using gulp or grunt

**Comment by handrews** [comment] 2024-05-24 01:27
Closing as duplicate of #508 (which is a slightly more general).

**Closed by handrews** 2024-05-24 01:27 UTC
Labels: re-use: ref-group-combine
