### ISSUE TITLE
Please permit optional path parameters

### ISSUE THREAD

**Issue by matjung** [OAI/OpenAPI-Specification#2258] opened 2020-06-07 11:24 UTC
required | boolean | Determines whether this parameter is mandatory. If the parameter location is "path", this property is REQUIRED and its value MUST be true. Otherwise, the property MAY be included and its default value is false.

In the specification for OpenAPI 3.x I noticed that path parameters must have required: true
I would like to suggest, that path parameters could also be optional e.g.
server.com/path/required/optional/optional
My implemented web service contains a path parameter which is optional
In my yaml I will state required: false

**Comment by MikeRalphson** [comment] 2020-06-07 11:35
Closing as as duplicate of #93 / #622 but feel free to continue the discussion there.

**Closed by MikeRalphson** 2020-06-07 11:35 UTC
