### ISSUE TITLE
Feature Request: $ref for servers object

### ISSUE THREAD

**Issue by shreelakshmijoshi** [OAI/OpenAPI-Specification#3129] opened 2023-01-06 10:17 UTC
In many use cases, there would be multiple APIs that would be associated with different servers. It would be great if the server could be referenced from a single server object under `components` and reused everywhere instead of overriding the `servers` object for each API.  
Currently,
```
  servers:
    - url: 'https://bookstore/v1'
      description: 'Get books from bookstore'
  paths:
     /book/{id}:
        get:
```
would result in API: `https://bookstore/v1/book/123`
But we also have the following apis that have server somewhere else, We'll have to override the global server variable in each of these paths which results in redundancy, maintenance issues when the server variables are changed.
```
  components:
     servers:
       - url1: 'https://bookstore/v1'
         description: 'Get books from bookstore'
       - url2: 'https://library/v2'
         description: 'Get books from library'
 
  $ref: "#/components/servers/url1"
  paths:
     /book/{id}:
        get:

     /libraryBook/{id}:
      $ref: "#/components/servers/url2"
        get:
        ...
        delete:
        ...

    /listLibraryBooks/
     $ref: "#/components/servers/url2"

```
Waiting to hear your thoughts!

**Comment by karenetheridge** [comment] 2023-01-08 01:50
Please could you fix the inconsistent indentation so it's valid yaml? it's difficult to understand what you're asking.

**Comment by shreelakshmijoshi** [comment] 2023-01-08 06:20
I fixed the indentation of both code blocks here:
Before,
```
components:
  servers:
    - url: 'https://bookstore/v1'
      description: 'Get books from bookstore'


paths:
  /book/{id}:
    get:
#      API -> GET: https://bookstore/v1/book/123

  /libraryBook/{id}:
    servers:
      - url: 'https://library/v2'
        description: 'Get books from library'
    get:
#      ....
#      API -> GET: https://library/v2/libraryBook/123
    delete:
#      ....
#      API -> DELETE: https://library/v2/libraryBook/123


  /listLibraryBooks/:
    servers:
      - url: 'https://library/v2'
        description: 'Get books from library'
    get:
#      API -> GET: https://library/v2/listLibraryBooks

```
After,
```
components:
  servers:
    - url1: 'https://bookstore/v1'
      description: 'Get books from bookstore'
    - url2: 'https://library/v2'
      description: 'Get books from library'


paths:
  /book/{id}:
    $ref: '#/components/servers/url1'
    get:
#      API -> GET: https://bookstore/v1/book/123

  /libraryBook/{id}:
    $ref: '#/components/servers/url2'
    get:
#      ....
#      API -> GET: https://library/v2/libraryBook/123
    delete:
#      ....
#      API -> DELETE: https://library/v2/libraryBook/123


  /listLibraryBooks/:
    $ref: '#/components/servers/url2'
    get:
#      API -> GET: https://library/v2/listLibraryBooks

```

**Comment by hkosova** [comment] 2023-01-09 14:12
Looks like a duplicate of #2338.

**Comment by handrews** [comment] 2024-01-27 04:14
Yes, closing this as a duplicate of #2338.

**Closed by handrews** 2024-01-27 04:14 UTC
Labels: $ref
