### ISSUE TITLE
Enum with maxlength/minlength 

### ISSUE THREAD

**Issue by shwetashukla** [OAI/OpenAPI-Specification#2153] opened 2020-02-21 21:07 UTC
Hi

Should maxlength/minlength be valid attributes with enum?

 "status": {
          "type": "string",
          "description": "pet status in the store",
          **"maxLength": 12,**
          "enum": [
            "available",
            "pending",
            "sold"
          ]
        }

Thanks
Shweta

**Comment by erunion** [comment] 2020-02-21 21:54
It kind of goes against the enum being there so I don't think so.

**Comment by shwetashukla** [comment] 2020-02-21 22:22
Yes you are correct , but is it specified in the specification . When i run the open api document against any validator it doesn't show any error

**Comment by webron** [comment] 2020-02-21 22:27
It's valid, it just doesn't really help much. If one of the enum values would be longer than 12 characters, that enum value will not be valid through validation..

**Comment by shwetashukla** [comment] 2020-02-21 22:37
Yup so should this be fixed in specification then so that  all other dependent tools like validators and code generators can also update as per specification?

**Comment by webron** [comment] 2020-02-21 22:55
What is there to fix?

**Comment by philsturgeon** [comment] 2020-02-24 06:05
I cannot imagine what a fix would be @shwetashukla, but regardless, OpenAPI v3.1 Schema Object (where the enum property is described) is JSON Schema. Seeing as this is valid JSON Schema, there is nothing to fix in OpenAPI. The conversation could be had on the [JSON Schema spec repo](https://github.com/json-schema-org/json-schema-spec), but the same question exists: I don't know if there's anything in the spec to fix there either.

**Comment by handrews** [comment] 2020-02-24 07:02
@philsturgeon @shwetashukla I'll state definitively that there is nothing to fix here.

JSON Schema does not forbid apparently-nonsensical combinations of attributes.  If you want to do that, a linter or a custom meta-schema is the appropriate place to decide what you want to forbid.

There are several reasons why this is allowed, but the most fundamental is that it keeps implementations simple.  You just evaluate all of the keywords you have, with no need to keep track of which keywords conflict with which other keywords.

**Comment by tedepstein** [comment] 2020-02-24 13:43
Right. Put another way, each JSON Schema assertion has independent veto power. A value has to pass all of the assertions in order to be valid. 

It's possible for a schema to include constraints that are redundant, overlapping, or even contradictory, making the schema unsatisfiable. But it's up to the schema designer, posssibly with the help of linters or other tools, to avoid these issues.

OpenAPI 3.1, currently in progress, aims to close the gap so that OpenAPI documents can use the full set of JSON Schema keywords. That's the direction, and we don't want to adopt any changes that would put OpenAPI out of step with JSON Schema. But there is an [Alternative Schema proposal](https://github.com/OAI/OpenAPI-Specification/blob/master/proposals/001_Alternative%20Schema%20Proposal.md) that would allow other schema languages to be used in OpenAPI. We could take up that proposal in a future version of the OpenAPI spec. 

@shwetashukla , hopefully we've addressed your concern, so I'll close this issue for now. If you feel the issue isn't really resolved, please feel free to reopen the issue and provide further comments.

**Closed by tedepstein** 2020-02-24 13:43 UTC

**Comment by shwetashukla** [comment] 2020-02-25 18:16
Thanks @tedepstein  @philsturgeon @handrews for the clarification
