### ISSUE TITLE
I'm using the HTTP `Link` header for pagination in my API.

### ISSUE THREAD

**Issue by Budda0ne** [OAI/OpenAPI-Specification#2448] opened 2021-01-23 16:36 UTC
I'm using the HTTP `Link` header for pagination in my API.

e.g. `GET /items?limit=10&filter=active`

returns a `Link`-header with `Link: <https://example.com/features?limit=10&filter=active&cursor=a34Dsdf>; rel="next"`

What I would like is for the auto-generation tools to be able to create a method e.g. "getNextPortion" that uses the parameters from the Link header to get the next n items.

Is this possible, or must I use "primitive" headers containing single integers and strings? 

__Originally posted by @meastp in https://github.com/OAI/OpenAPI-Specification/issues/2402__

**Comment by MikeRalphson** [comment] 2021-01-23 17:04
Dupe of #2402

**Closed by MikeRalphson** 2021-01-23 17:04 UTC
