### ISSUE TITLE
Introduce tags hierarchy

### ISSUE THREAD

**Issue by dtsaryov** [OAI/OpenAPI-Specification#1507] opened 2018-03-12 10:17 UTC
Hello.

My proposal is to add an ability to create tags hierarchy, for example:

```yaml
tags:
  - name: Entites
    description: CRUD entities operations
      - User
      - Group
  - name: Services
    description: Predefined queries execution
      - FooService:
        - name: ...
          description: ...
      - BarService:
        - name: ...
          description:
```

It'll help to group operations in case of generic REST API.

**Comment by MikeRalphson** [comment] 2018-03-12 10:36
See also #1367

**Comment by ymohdriz** [comment] 2018-03-15 07:05
Hi @prozac631,

If I understood correctly, open api provides a way to tag in operation level. Hope we can group operations by using operation level tagging.
Let me know if your requirement is completely different.

Thanks,
Mohammed

**Comment by prozac631** [comment] 2018-03-16 05:09
Hi @ymohdriz 

Yes, we can use grouping for operations, but it would be nice if we could group operations inside of group of operations. Let me make it more clear.

For example, you have operations and their paths have the following template: `/entities/*` (`entities/User`, `entities/Group`, etc).

And in the same time you have a set operations that can be performed with these entities, for example: `entities/User/create/`, `entities/User/get/`, `entities/User/delete`, etc.

And in this case we can create a tag `Entities` and sub tags `User`, `Group`, etc.

**Comment by maaland** [comment] 2018-07-30 13:04
I support the request for sub-tags. I want to be able to group (or at least sort) the methods under each of my endpoints, and as far as I can tell, that's not possible right now.

**Comment by silkentrance** [comment] 2018-08-03 22:12
See also #1642. The path is already a physical group, why do you need an indirection for it?

**Comment by jukeblimp32** [comment] 2018-09-18 22:47
I really need subtags. My current tags are getting far to cluttered.

**Comment by farmbotgianpaolo** [comment] 2018-11-29 02:51
I support the request for sub-tags or tag hyerarchy. The reason is simple: if I have a single endpoint where I built public and private APIs I would like to group them into these 2 categories.

**Comment by storm367** [comment] 2020-01-24 09:31
Tag Hierarchy doesn't seem to be supported yet? I support this request to add sub-tags.

**Comment by dschmide** [comment] 2020-02-06 08:29
Adding sub-tags is ab obvious advantage. Remember, there is no search and filter option for the apidocs, so this tagging system is all we can provide to devs. 
At this point, my co-workers are telling me to add subgroups, and not believing me when I tell them that "its not possible", but sadly, this is a reality.
I started embedding "tags" right in the paths so the structure within tags is at least somewhat preserved by abusing the alphabetical ordering - but this is clearly a symptom of a lack of feature.

**Comment by kael-shipman** [comment] 2020-04-20 20:23
I support this, and furthermore support closing this issue as a duplicate of #1367 so that we can keep the conversation in one place. Adding my comments over there.

**Comment by handrews** [comment] 2024-04-25 18:00
Closing as recommended as a duplicate of #1367 - please continue the conversation there!

**Closed by handrews** 2024-04-25 18:00 UTC
Labels: review
