### ISSUE TITLE
Support for Constant Value in API

### ISSUE THREAD

**Issue by duckladydinh** [OAI/OpenAPI-Specification#1620] opened 2018-06-29 15:21 UTC
Since OpenAPI can be used to generate client code, it is good to support some constant value in the API itself.

Use case: When you add type info to a class as a properties, we need that property for deserialization and the value of this property will never change.

**Comment by MikeRalphson** [comment] 2018-06-29 15:24
Can you not do this with an `enum` property which only has one value?

```yaml
MySchema:
  type: object
  properties:
    MyProperty:
      type: string
      enum:
      - constantValue
```

**Comment by hkosova** [comment] 2018-06-29 17:18
Possibly related: #1313

**Comment by marcusbesjes** [comment] 2018-10-18 11:36
> Can you not do this with an `enum` property which only has one value?

Yes thats how it needs to be done now, but it's a bit verbose and it doesn't look nice in your documentation (generated web pages), where it will show as an expandable list of one item VS just the string value.

**Comment by MikeRalphson** [comment] 2018-10-18 12:55
Closing, as this is a dupe of #1313 as @hkosova observed.

**Closed** 2018-10-18 12:55 UTC
