### ISSUE TITLE
Feature suggestion: Server object add name property

### ISSUE THREAD

**Issue by tanmen** [OAI/OpenAPI-Specification#2229] opened 2020-05-12 08:52 UTC
Hello.
I think should be server object add name property.
because server object identification only url.
I think short identify properties should be created for generated code.

I am Japanese and have never learned English.
I'm sorry if i have rude remark.

**Comment by MikeRalphson** [comment] 2020-05-12 10:46
Hi @tanmen, your issue is definitely not rude and is completely understandable. However, this issue has been raised before and so this is a duplicate of issue #1821. Please join in the conversation / add a reaction on that issue.

**Closed by MikeRalphson** 2020-05-12 10:46 UTC

**Comment by tanmen** [comment] 2020-05-12 10:47
Thank you:)
its ok.
