### ISSUE TITLE
API specific description for parameter

### ISSUE THREAD

**Issue by BabuGiri** [OAI/OpenAPI-Specification#1352] opened 2017-09-19 12:27 UTC
Hi in below example i have a need to add different description to "skipParam" describing in the context of the corresponding API "testAPI1" and "testAPI2", is this possible in swagger 2.0 or 3.0.0?

one option i see is duplicate parameter definition in each of the API but that is going to put lot of burden on future maintenance when more number of API's are going to have same reused except few proprieties like description is different.
{
  ....
  "parameters": {
    "skipParam": {
      "name": "skip",
      "in": "query",
      "description": "number of items to skip",
      "required": true,
      "schema": {
        "type": "integer",
        "format": "int32"
      }
    }
  },
  ....
  "paths": {
    "/testAPI1": {
      "get": {
        "responses": {
          "200": {
            "description": "success response",
            "schema": {
              "$ref": "#/definitions/TestObject1"
            }
          },
          "500": {
            "description": "Error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/parameters/skipParam"
          }
        ]
      }
    },
    "/testAPI2": {
      "get": {
        "responses": {
          "200": {
            "description": "Success response",
            "schema": {
              "$ref": "#/definitions/TestObject2"
            }
          },
          "500": {
            "description": "Error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/parameters/skipParam"
          }
        ]
      }
    }
  }
  ....
}

**Comment by darrelmiller** [comment] 2017-09-19 13:19
This is a commonly requested feature and unfortunately it is not an easy problem to solve.  We are waiting to see how JSON Schema resolves the same issue and how the community responds to their solution before adopting any new mechanism.

In the meanwhile, you can look at this from a positive perspective.  Having a parameter that is named the same but having a different behavior (that's why you would want a different description, right?) could be particularly confusing to your end users.  Also, when writing code to implement the handling of parameter on the client and the server, it is better to have a consistent implementation of the behavior.  The last thing anyone wants to deal with is the complexity of implementation inheritance in query parameters!

**Comment by BabuGiri** [comment] 2017-09-19 14:38
Agree behavioral changes are going to be confusing, above I was mainly looking for description field to describe parameter in API context for better documentation of parameter.

With schema object which follows JSON schema conventions may not have this problem as allOf along with $ref can be used to achieve same

**Comment by MikeRalphson** [comment] 2017-09-22 13:19
Duplicate of #556

**Closed** 2017-09-26 12:25 UTC
