### ISSUE TITLE
Why tags not add children property?

### ISSUE THREAD

**Issue by charlesluo2014** [OAI/OpenAPI-Specification#2449] opened 2021-01-23 16:41 UTC
When we want to define a tag,and want to add a child tag to it ,now it dose not support!

**Comment by MikeRalphson** [comment] 2021-01-23 17:07
This looks like it might be a duplicate of #1507 / #1367. If not, please let us know and we will re-open this issue. Thanks.

**Closed by MikeRalphson** 2021-01-23 17:07 UTC
