### ISSUE TITLE
Add global parameters that apply to all paths

### ISSUE THREAD

**Issue by costeaalex** [OAI/OpenAPI-Specification#2357] opened 2020-09-21 16:52 UTC
This is somewhat of an oversight by I think it would be a very handy thing to be able to define global custom headers (which is what I need and found a couple of others needing) and have them apply to all requests. Cluttering the paths with refs is not very maintainable nor efficient.

Thanks

**Comment by MikeRalphson** [comment] 2020-09-23 09:12
This is a duplicate of the (closed) issue #1577 - see ongoing discussions in #445 #1466 .

**Closed by MikeRalphson** 2020-09-23 09:12 UTC

**Comment by costeaalex** [comment] 2020-09-23 09:27
Mike, my nipples do not explode with delight as these issue don't seem to specifically address the global parameter problem. In one of them it's about grouped parameters and the other has shifted towards referenced parameters rather than global parameters so I am afraid this will fly under the radar and not really be clearly addressed. Am I wrong in assuming this?

I see in the ticket with global parameters the concern is with exceptions to requests for the global parameters but that one is closed and in the other ones there isn't talk of global parameters per se.

**Comment by MikeRalphson** [comment] 2020-10-07 15:41
@costeaalex I just wanted to point you at the issues flagged up when this was last raised in #1577 - it's unlikely the avenues being considered have changed since the last time it came up (i.e. global doesn't mean global all the time, and traits / groups of parameters are more in line with the way we see the spec. evolving in the future).

**Comment by Amilpuy** [comment] 2023-05-20 03:04
> 对于大型项目而言,大量的$ref真的非常难以使用,不是我对业务模块拆分的还不够细,而是功能性的接口真的太多,就没有什么方式来支持所有路径配置这类方式？en:(对于大型项目，大量的$ref确实很难用，不是因为我对业务模块分解的不够，而是因为功能接口太多，没有办法支持所有路径配置等方法？),大量的谷歌之后我发现,对于Spring Boot 3.0以上以上真的没有其它更好的选择,要么只能接受现状,要么进行大量的编码！(谷歌了很多之后，发现Spring Boot 3.0+以上真的没有更好的选择了，要么接受现状，要么做大量编码！)

now：[Add global customizer and filters #1616](https://github.com/springdoc/springdoc-openapi/pull/1616)
