### ISSUE TITLE
bug: [golang] oepnAPI generate function does not write http.ResponseWriter correctly

### ISSUE THREAD

**Issue by chengkai-c** [OAI/OpenAPI-Specification#3982] opened 2024-07-30 22:25 UTC
Hi All, I would like to double check if this is a bug or just Im miss using the function.

I am trying to generate a Response with `oneOf`:
```
  responses:
    200:
      description: Entity objects.
      content:
        application/json:
          schema:
            $ref: "schemas.yml#/Response"
```
```
Response:
  oneOf:
    - $ref: '#/A'
    - $ref: '#/B'
```
Where you can think of `A` and `B` are two different Object

and the generate response is as following
```
type Response struct {
	union json.RawMessage
}

type RetrieveAnEntity200JSONResponse Response

func (response RetrieveAnEntity200JSONResponse) VisitResponseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}
```

The issue I found is, the `VisitResponseResponse` did not Encode the response correctly to `http.ResponseWriter`(meaning that, the `http.responseWriter` will have empty body).

I tried to debug and found out that the potential reason is because `union` is in lowercase. This means that `union` becomes invisible, and thus the Encode function can't access it, resulting in an empty body.

When I modify `api.gen.go` and change the `union` to upper case `Union`, then this problem is resolved.(I know I should not modify this file but this is only for debug purpose)

Does any one have any thought's about it? or did I do something wrong here.

Thank!

**Comment by handrews** [comment] 2024-07-30 22:47
Hello @chengkai-c — this repository is for the OpenAPI _Specification_ itself.  We do not support any implementations, and this looks like an issue you should raise with the tool/library implementor.

I can confirm that you are using `oneOf` correctly.  Since I don't see a specification question here, I'm going to go ahead and close this, but please feel free to comment if I have missed something and I will re-open it.

**Closed by handrews** 2024-07-30 22:47 UTC
