### ISSUE TITLE
Swagger for Server Sent Events

### ISSUE THREAD

**Issue by bmeck** [OAI/OpenAPI-Specification#396] opened 2015-06-17 16:42 UTC
It would be nice if Swagger supported [Server Sent Events](https://en.wikipedia.org/wiki/Server-sent_events). Which is a Uni-directional alternative for streaming content. This still would fall within REST to my knowledge (in particular due to last seen ID). A more concrete example can be seen at [HTML5Rocks](http://www.html5rocks.com/en/tutorials/eventsource/basics/)

semi-related : #55

**Comment by buremba** [comment] 2015-09-22 15:01
+1

**Comment by wiltshiretom** [comment] 2015-10-27 14:30
+1!

**Comment by buremba** [comment] 2015-11-18 01:56
+1

**Comment by casualjim** [comment] 2015-12-03 04:57
I think you can kind of represent it (without tooling support though) like this

```yaml
paths:
  /:
    get:
      produces: ["text/event-stream"]
      responses:
        default:
          description: example of defining events for sse 
            schema:
              type: object
              x-events:
                added:
                  type: object
                  properties:
                    message:
                      type: string
                    createdAt:
                      type: string
                      format: date-time
                updated:
                  type: object
                    properties:
                      previous:
                        type: string
                      newValue:
                        type: string
                      updatedAt:
                        type: string
                        format: date-time
```

**Comment by elbrujohalcon** [comment] 2015-12-11 18:20
+1

**Comment by akoroljov** [comment] 2015-12-15 07:31
Well. But why you need to represent it in swagger without tooling support? Does it have any use cases?

**Comment by casualjim** [comment] 2015-12-15 15:09
step 1, make the proposal to start the discussion

**Comment by lieldulev** [comment] 2016-02-09 17:03
:+1:

**Comment by ikitommi** [comment] 2016-02-23 21:13
:+1:

**Comment by mrhornsby** [comment] 2016-03-01 13:20
:+1:

**Comment by casualjim** [comment] 2016-03-02 00:41
parent: #586

**Comment by jroper** [comment] 2016-05-03 05:26
I don't think this should be limited to uni directional streaming.  While of course, web browsers and many existing HTTP implementations require a request to be fully consumed/produced before sending/reading the response, HTTP itself does not impose this limitation, nor does anything about the SSE protocol, and so there's no reason why two services using an HTTP client/server implementation that supports it can't speak SSE both up and down at the same time.

Another reason why it shouldn't be limited to uni directional streaming is that this and a possible WebSockets streaming extension could share a lot in common, it would be a shame to have two completely different ways of specifying an SSE stream vs a WebSocket event stream.

**Comment by dolmen** [comment] 2016-05-17 17:25
@jroper:
- With HTTP you don't have a bidirectional link over a single TCP connection: the client speaks first and the server answers.
- A link over WebSockets is not HTTP anymore, so I think it is out of scope for Swagger/OpenAPI.

Personally, over a bidirectionnal link (TCP or WebSocket) I would use JSON RPC 2.0 for fully asynchronous dialog, not Event Source.

**Comment by jroper** [comment] 2016-06-03 04:29
> With HTTP you don't have a bidirectional link over a single TCP connection: the client speaks first and the server answers.

That's not actually true.  There is nothing in the HTTP spec that says that a server has to fully consume a client request before it starts sending the response, in fact, the spec actually has provisions that allow for this to be done, from [section 8.2.3](https://tools.ietf.org/html/rfc2616#section-8.2.3):

> If an origin server receives a request that does not include an Expect request-header field with the "100-continue" expectation, the request includes a request body, and the server responds with a final status code before reading the entire request body from the transport connection, then the server SHOULD NOT close the transport connection until it has read the entire request, or until the client closes the connection.

This implies that the server is allowed to send a response before the entire request body is read.  So bidirectional communication over a single TCP connection is definitely allowed.  A number of asynchronous HTTP servers (eg akka-http, Netty) do explicitly support this too.

**Comment by fzanaroli** [comment] 2017-04-06 14:01
+1

**Comment by allandenis38** [comment] 2017-04-06 14:04
+1

**Comment by dominiquemongelli** [comment] 2017-04-06 15:16
+1

**Comment by loriepisicchio** [comment] 2017-04-07 07:23
+1

**Comment by jfmarquet** [comment] 2017-04-07 08:00
:+1:

**Comment by EricPiasentin** [comment] 2017-04-07 08:02
+1

**Comment by benjaminranc** [comment] 2017-04-07 08:38
+1

**Comment by dolmen** [comment] 2017-04-07 16:11
Please stop those polluting `+1` and use instead [built-in reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) on the original submission.
Do you know that you can even delete your own useless comments?

**Comment by jroper** [comment] 2017-04-09 23:18
Getting everyone in your company to +1 an issue is the dumbest strategy ever, as a maintainer of a number of open source projects, when I see lots of noise on an issue, and then I see most of that noise is from one company, it leads me to believe that that company is the only company that wants the feature, which leads me to deprioritise the issue. Please streamdata.io, there are serious people here who are serious about wanting to see this become part of the spec and want to have serious discussion about it, the only thing you're doing is hurting our efforts.

**Comment by darrelmiller** [comment] 2017-04-10 01:36
Now that V3 supports OneOf in JSON Schema, I'm not exactly sure what it is that people want more from OpenAPI in order to describe SSE payloads.  Perhaps if someone could describe the challenges currently faced then we would have a better idea as to what needs enhancing.

**Comment by allandenis38** [comment] 2017-04-10 06:45
Sorry @jroper, our intent was not to hurt your efforts at all. In order to show that you are also serious people ;-) we will remove those useless +1 and use reactions instead.

**Comment by jroper** [comment] 2017-04-10 10:21
@darrelmiller SSE events have a few properties, and these are not JSON properties, they are part of the SSE protocol. Most interesting to OpenAPI is the `event` and `data` properties.  The `data` property is the payload, this would typically contain the event data as JSON, or maybe as a plain text string. The `event` field however contains the events type. So, to support **idiomatic** SSE, OpenAPI would have to allow specifying multiple event types, most likely with a schema for each.

A non idiomatic approach could be taken where the OneOf JSON schema support is used with no event type, but even then there are a few questions that should probably be answered by the spec to allow tooling to generate interoperable implementations.  For example, how should an OpenAPI spec indicate that SSE is being used? By listing `text/event-stream` in the `produces`?  What if the spec lists both `text/event-stream` and `application/json` in the `produces`? How should a tool interpret that? Because in one case, a client code generator will need to generate a method that returns the object directly, and in the other it would need to return a stream.  And if `text/event-stream` is listed in `produces`, how does the client then know that the contents of `text/event-stream` of the data payload is `application/json`, or `text/plain`?

**Comment by dolmen** [comment] 2017-04-11 12:54
In my use case I want to return `text/event-stream` for status 200, but `application/json` for other statuses (structured error reporting for bad usage of the API or internal errors).
For now I'm specifying this by cheating with the `headers` property of a `Response` object. But I do not expect Swagger clients to properly handle that.
```yaml
      produces: ["text/event-stream","application/json"]
      responses:
        '200':
          description: Stream is starting
          x-produces: ["text/event-stream"]
          headers:
            'Content-Type':
              type: string
              enum: ["text/event-stream"]
        default:
          $ref: '#/responses/DefaultError'
```

**Comment by whitlockjc** [comment] 2017-04-12 17:26
What is really being discussed _(in my opinion)_ is how one would use OAS to describe a streaming API, regardless of which technology _(SSE, WebSockets, ...)_ you're using.  Since all of these technologies all use HTTP, the OAS already has the primitives in place so we just need to decide is at what level we want to add support to the OAS, and what that looks like.

In a recent discussion with @darrelmiller, the main question I needed answered was to the following: _"When describing a streaming API via OAS, is the response schema suppose to describe each "chunk" of the response or for the response as a whole?"_  This came up when looking at the OAS for the [Kubernetes API](https://kubernetes.io/docs/api-reference/v1.6/#watch-402).  For their OAS usage, the response schema was written to describe each _chunk_ in the stream as a JSON Object.  To me, this is intuitive **but** from a tooling perspective, there is no way for the tooling to know that this is a streaming API and would potentially have an issue where it could fail to validate appropriately in all situations.

My hope in answering this is for consistency, so OAS users know that there is a well-defined approach for documenting streaming APIs.

**Comment by dolmen** [comment] 2017-04-13 23:09
@whitlockjc For [SSE](https://html.spec.whatwg.org/multipage/comms.html#server-sent-events) we want to be able to describe multiple types of chunks (called *events*), each being identified by an event name. So if events are sent are JSON, the spec format should allow to describe the schema of the message for each event name.

**Comment by darrelmiller** [comment] 2017-04-13 23:18
@dolmen Would it be sufficient to be able to indicate that the payload schema only applies to a "chunk" and then use oneOf in JSON Schema to define all of the events?
The other option might be to have a `chunkSchema` property that is an array of schema objects.  The end result is effectively the same though.  At least by using oneOf a JSON Schema validator could validate all the chunks using a single schema.

**Comment by allandenis38** [comment] 2017-04-14 06:50
@darrelmiller In case of SSE, an event contains non-JSON properties and this is true for every event/chunk. So applying a JSON validation to the entire event would not make sense but rather the value of an SSE property.

**Comment by darrelmiller** [comment] 2017-04-14 14:18
@allandenis38 Unfortunately OpenAPI is currently limited in its ability to describe non-JSON payloads.  If we can fix that then we would be a step closer to being able to describe things like SSE.  I don't believe it would be wise to try and address the description of SSE events without first addressing the larger issue.

**Comment by whitlockjc** [comment] 2017-04-14 15:35
@dolmen I agree.  Many of the WebSocket APIs I've seen can have multiple message types for the same event.

@allandenis38 While @darrelmiller is right about the limitations of OAS describing non-JSON payloads, for unstructured data or data that is composed of JSON primitives _(composite values, etc.)_, you could still use OAS to describe your types.  For example, OAS won't help much with XML but if you are sending back strings that follow a particular pattern or regex, OAS might still be able to help.

**Comment by jroper** [comment] 2017-04-18 00:49
@darrelmiller while yes OpenAPI is limited in its ability to describe non-JSON payloads, note that the SSE event type is quite a different problem to say, wanting to describe an xml or protobuf payload, since the payload of an SSE event will generally still be JSON, it just has this other attribute outside of the JSON that impacts the interpretation of the data. So I don't think that fixing Swaggers ability to describe non-JSON payloads will necessarily gain us a useful solution to providing support for idiomatic SSE usage.

For example, one way to support SSE's event type would be to augment the `discriminator` property in a schema, where you could give it a special value, say `discriminator: $sseEvent`, rather than `discriminator: petType`, and that will use the SSE event field, rather than the `petType` field in the JSON, to discriminate between different types of events. So then on the wire, an SSE stream of pets (from the pet store example) might look like this:

```
event: Cat
data: {"name":"Mittens"}

event: Dog
data: {"name":"Fido"}
```

And the first event would be deserialized as a `Cat`, the second as a `Dog`.

**Comment by fizxmike** [comment] 2018-09-14 16:46
My use case (and maybe others') is REST + SSE updates. So, given an API endpoint (say, get all X or get X by id), I would like to also subscribe to the X subject/topic. Maybe this can help in your design. 

Should we just be moving to REST over WebSockets? I think OpenAPISpec is still compatible so long as "data" is JSON. It seems that http(s) GET,POST, etc. could just be replaced with "event" types... Thoughts?

**Comment by ragazzojp** [comment] 2019-05-14 15:28
As mentioned above, I think it's possible to do it if we generalize the support for non-JSON data. As simple types like integer and strings are the same when encoded in "text" instead of JSON, the only difference is made by `object` and `array`. We could add `format` also to them, enabling things like:

```yaml
/events:
  get:
    responses:
      200:
        content:
          text/event-stream:
            schema:
              type: array # eventually also stream as new type
              format: text-chunked # or whatever other keyword to mean HTTP-header-style encoding separated by empty lines
              items:
                type: object
                required:
                  - id # not strictly required by SSE, but it's an example
                  - event # not strictly required by SSE, but it's an example
                  - data
                properties: # also possible to model with oneOf+discriminator
                  id:
                    type: integer
                    description: my event id
                  event:
                    type: string
                    description: my event type
                  data:
                    type: object # object = JSON, otherwise string, integer, ...
                    format: json # JSON is by default, but we may have different format as proposed above for the array
                    required:
                      - a
                      - b
                    properties: # as usual
                      a: # ...
                      b: # ...
                      c: # ...
```

Note that this is not strictly limited to SSE. Enabling `format` for `array` and `object` may have this and other applications. SSE protocol is modeled manually.

**Comment by barrycaceres** [comment] 2020-01-29 19:39
This thread is a few years old now and I see it was referenced in August of 2019 and I have not seen anything in the Open API spec that does support SSE (unless I am missing it).

For me, I use SSE as an **option** when the client is uploading a large file to be processed by the server.  The caller controls this with the `Accept` header.

If the caller sends in **no** `Accept`, or `Accept: */*` or `Accept: application/json` (or similar) then the operation works the same as Swagger/Open API would normally expect.

- on a 200 it would return something like a `FileProcessedResponse` object (as defined in my schema) to describe the results of processing the file that was uploaded.

- on a `4xx` or `5xx` it would return an `ErrorResponse` to describing why the file could not be processed

Typically if the file could only be partially processed (i.e.: it contains both good records and bad records) the response is a `200` with the `FileProcessedResponse` object describing how many succeeded and what failed.

That said... in the event the client sends `Accept: text/event-stream` instead, then I produce the following events....

`progress` -- which contains the `FileProcessedResponse` in the `data` segment but indicating values for what has been done "so far"

`completed` -- same as the `200` response above, this is the final resultant `FileProcessedResponse` object

`aborted` -- same as the `4xx` or `5xx` response above -- the `data` segment of the event is my `ErrorResponse` object indicating why things ultimately failed.


So the SSE events for the end point very much correlate to the normal the Swagger/OpenAPI definition of the `200`, `4xx` and `5xx` responses.  So I am wondering if following this model would make it easier to describe things in OpenAPI.  Something as simple as a `providesSSE` flag which can be set to `true` or `false` (defaults to `false`) and then for each response code correlate it to an SSE event type instead... so the SSE response is always a `200` but the actual events indicate the success and failure.

**Comment by dkirrane** [comment] 2020-02-07 11:54
Duplicate https://github.com/OAI/OpenAPI-Specification/issues/770

**Comment by davix** [comment] 2020-03-17 05:51
> I think you can kind of represent it (without tooling support though) like this
> 
> ```yaml
> paths:
>   /:
>     get:
>       produces: ["text/event-stream"]
>       responses:
>         default:
>           description: example of defining events for sse 
>           schema:
>             type: object
>             x-events:
>               added:
>                 type: object
>                 properties:
>                   message:
>                     type: string
>                   createdAt:
>                     type: string
>                     format: date-time
>               updated:
>                 type: object
>                   properties:
>                     previous:
>                       type: string
>                     newValue:
>                       type: string
>                     updatedAt:
>                       type: string
>                       format: date-time
> ```

Hi, it seems still uncertain whether or when it will be supported, but we may need some workaround right now.

Does anybody know workaround how to describe SSE with swagger file?

I can give up its functionalities (like code generation) and just use swagger file as a document.

I tried the method in earlier comment, but the generated output doesn't look like a SSE output.

Here's generated:
![image](https://user-images.githubusercontent.com/2516468/76825996-532aa000-6856-11ea-80b1-21fa535cb5d4.png)

Here's expected:
```
event: Cat
data: {"name":"Mittens"}

event: Dog
data: {"name":"Fido"}
```

**Comment by ihakh** [comment] 2020-06-06 04:14
> This thread is a few years old now and I see it was referenced in August of 2019 and I have not seen anything in the Open API spec that does support SSE (unless I am missing it).
> 
> For me, I use SSE as an **option** when the client is uploading a large file to be processed by the server. The caller controls this with the `Accept` header.
> 
> If the caller sends in **no** `Accept`, or `Accept: */*` or `Accept: application/json` (or similar) then the operation works the same as Swagger/Open API would normally expect.
> 
> * on a 200 it would return something like a `FileProcessedResponse` object (as defined in my schema) to describe the results of processing the file that was uploaded.
> * on a `4xx` or `5xx` it would return an `ErrorResponse` to describing why the file could not be processed
> 
> Typically if the file could only be partially processed (i.e.: it contains both good records and bad records) the response is a `200` with the `FileProcessedResponse` object describing how many succeeded and what failed.
> 
> That said... in the event the client sends `Accept: text/event-stream` instead, then I produce the following events....
> 
> `progress` -- which contains the `FileProcessedResponse` in the `data` segment but indicating values for what has been done "so far"
> 
> `completed` -- same as the `200` response above, this is the final resultant `FileProcessedResponse` object
> 
> `aborted` -- same as the `4xx` or `5xx` response above -- the `data` segment of the event is my `ErrorResponse` object indicating why things ultimately failed.
> 
> So the SSE events for the end point very much correlate to the normal the Swagger/OpenAPI definition of the `200`, `4xx` and `5xx` responses. So I am wondering if following this model would make it easier to describe things in OpenAPI. Something as simple as a `providesSSE` flag which can be set to `true` or `false` (defaults to `false`) and then for each response code correlate it to an SSE event type instead... so the SSE response is always a `200` but the actual events indicate the success and failure.

I think this is a very good point to start
three type of JSON OK event for start and progress and complete
and one or more type of ERROR event

> step 1, make the proposal to start the discussion

the proposal of @barrycaceres seems ok to implement

**Comment by davide1995** [comment] 2020-08-06 23:01
Any update on this? I don't want always to use EventSource.addEventListener('message') manually. I would like to expect that when I call this.service.myObservable().subscribe(), it works in the right manner even with text/event-stream

**Comment by philsturgeon** [comment] 2020-11-03 09:54
Now we have callbacks and websockets I'd call this done.

**Comment by jhpratt** [comment] 2020-11-03 09:56
@philsturgeon Callbacks and websockets are completely different than SSE.

**Comment by philsturgeon** [comment] 2020-11-03 10:22
I meant webhooks but yep there's a bunch of server emitted things supported and there's plenty of other issues describing other forms #523 https://github.com/OAI/OpenAPI-Specification/issues/770

Let's talk about Server Push on the Server Push issue and anything else can have a more specific issue.

**Comment by jhpratt** [comment] 2020-11-03 10:26
Server sent events _is_ more specific than push events. Not to mention the fact that this thread is where all discussion has taken place.

**Comment by philsturgeon** [comment] 2020-11-03 10:59
There’s a lot of duplicates floating around so I’ve closed #1499 instead. We can give this another 5 years to see if it makes any progress. ;)

**Comment by philsturgeon** [comment] 2020-11-03 11:01
The point isn’t if they’re the exact same use case or not, more that trying to support every single type of everything makes OAS a kitchen sink spec, and there’s clearly not much progress or interest. It’s never come up at work either, and we get every type of request you could imagine. 

As you’re clearly really interested in it, I’d suggest making a proposal and seeing how far you can get it. Nobody will do it, as can be seen from the inactivity so far.

**Comment by enhsaihan-d** [comment] 2021-05-14 09:22
I'm quite baffled how this hasn't been implemented yet considering with how SSE is becoming more popular with rise of reactive systems

**Comment by philsturgeon** [comment] 2021-05-14 15:01
> I'm quite baffled how this hasn't been implemented yet with how SSE is becoming more popular with rise of reactive systems

It’s not been added because you haven’t added it. 

https://github.com/OAI/OpenAPI-Specification#participation

**Comment by ahopkins** [comment] 2021-08-07 21:01
+1

**Comment by darrelmiller** [comment] 2021-08-07 23:42
The best way to get this formalized in the OpenAPI specification is for the users of SSE to get some agreement on a standard way of describing the event stream.  There are a couple of reasonable suggestions so far, but let me add a slight variant to the one proposed by @ragazzojp .

```yaml
/events:
  get:
    responses:
      200:
        content:
          text/event-stream:
            schema:
              type: array 
              format: event-stream
              items:
                oneOf:
                    - type: object
                      properties:
                         id:
                           type: string
                         event: 
                           const: cat
                         data: 
                           type: object
                           properties: 
                             name:
                               type: string
                    - type: object
                      properties:
                         id:
                           type: string
                         event: 
                           const: dog
                         data: 
                           type: object
                           properties: 
                             name:
                               type: string
                    
```

The OpenAPI specification has precedent for using JSON schema to model formats that are not JSON (e.g. form -url-encoded).  I don't see it as outside the realms of possibility to use JSON schema to describe the shape of each event. A constant value can be used for the event property if events are being sent.  Any complex structure described by the data field would need to be be serialized on a single line.  These types of rules could be defined in the OpenAPI specification for mapping JSON Schema to the text/event-stream media type.  What would be event better is if this mapping were done in a separate specification and then the format keyword used to indicate the use of a special serialization.  Although, I'm not sure how enthusiastic the JSON Schema folks would be about this.

I think the community who are interested in SSE can get 90% of the way towards a solution that describes server sent events using OAS as it currently stands.  Once there is agreement on the best way to do that, standardizing that approach in the OAS spec may help with adoption and tooling.

**Closed** 2022-02-24 17:40 UTC
Labels: OpenAPI.Next Proposal, Sub Issue

**Comment by ahopkins** [comment] 2022-02-24 17:42
Why closed?

**Comment by darrelmiller** [comment] 2022-02-24 17:58
There have a been a couple of suggestions of how to model SSE in OpenAPI.  SSE is just a long polling HTTP GET with a payload that supports sending discrete elements of data.

**Comment by twhittock** [comment] 2022-04-25 12:28
https://github.com/OAI/OpenAPI-Specification/issues/396#issuecomment-894718960 is this the canonical way to represent SSE, then? And we bypass any tooling to write the handler manually?

**Comment by philsturgeon** [comment] 2022-04-26 11:45
After years of inactivity I invited the community interested in SSE to get involved in May 2021. Nobody did.

Then in August 2021 @darrelmiller invited the community interested in SSE to participate. Nobody did. 

Be the change you want to see. 🙌🏻

https://github.com/OAI/OpenAPI-Specification#participation

**Comment by twhittock** [comment] 2022-04-27 09:21
I'm not sure what it means for me to be the change I want to see @philsturgeon - is there a specific issue with considering the proposal in https://github.com/OAI/OpenAPI-Specification/issues/396#issuecomment-894718960 canonical for SSE, as I suggested?

The participation section you link to states that we should "Check the [issues](https://github.com/OAI/OpenAPI-Specification/issues) and [pull requests](https://github.com/OAI/OpenAPI-Specification/pulls) to see if someone has already documented your idea or feedback on the specification", which surely is what is happening when people contribute to this issue, but it keeps getting closed by members of the project.

Perhaps this falls under "Not all feedback can be accommodated and there may be solid arguments for or against a change being appropriate for the specification" - if so, why not explain that Open API will not support SSE and give those solid arguments against it?

I genuinely don't know what you expect to see.

**Comment by philsturgeon** [comment] 2022-04-27 09:39
I was pointing you to the weekly calls:

> The TSC holds weekly web conferences to review open pull requests and discuss open issues related to the evolving OpenAPI Specification. Participation in weekly calls and scheduled working sessions is open to the community. You can view the entire OpenAPI [technical meeting calendar](https://calendar.google.com/calendar/u/0/embed?src=c_fue82vsncog6ahhjvuokjo8qsk@group.calendar.google.com) online.

**Comment by giowe** [comment] 2023-01-11 16:46
any update?

**Comment by twhittock** [comment] 2023-01-11 21:08
No, I attended one of the calls which was cut off early due to key people not attending and no proposals were entertained. I get the feeling it's really out of scope for this project, so I just gave up and rolled my own.

**Comment by giowe** [comment] 2023-01-12 09:20
@twhittock do you have something I can see to share ?

**Comment by shalberd** [comment] 2023-10-03 18:46
@philsturgeon this is very disappointing and probably more of a communication- and approach problem. We, too, are using Server Sent Events. It is a clear part of http and API frameworks. The facts that it cannot be described in OpenAPI is deplorable.

**Comment by jroper** [comment] 2023-10-04 00:20
@shalberd Using words like "deplorable" and "disappointing" is not the way to engage in an open source community. Please adjust your tone. @philsturgeon has invited anyone that wants to take the lead on putting this into the spec to join the weekly calls and do so. That includes *you*. Open source projects only work when community members that need features step up and engage to help provide those features. When you tell an open source project they are disappointing and deplorable for not adding a feature that they are happy to accept from a contributor, but don't volunteer to contribute yourself, you're actually pointing the finger at yourself, calling yourself disappointing and deplorable.

**Comment by hasufell** [comment] 2023-10-04 02:52
I think the signals from the maintainers of this project are not too clear. First off: this ticket has been closed as "completed". Why? Where's the "call for help" exactly?

**Comment by jroper** [comment] 2023-10-04 03:23
It was not closed as "completed". The GitHub close reason feature went live in [May 2022](https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/), with the preview starting for a few projects in March 2022. This was closed in [February 2022](https://github.com/OAI/OpenAPI-Specification/issues/396#event-6133899980). Completed is just the default reason. All issues that were closed prior to when the close reasons feature was added to GitHub have the reason of completed. For example, [this issue from 2014](https://github.com/OAI/OpenAPI-Specification/issues/13) was also closed as "completed", 8 years prior to the ability to specify a close reason in GitHub.

As for the calls for help, just read through the comment history. [Here's one](https://github.com/OAI/OpenAPI-Specification/issues/396#issuecomment-721047714), [here's another](https://github.com/OAI/OpenAPI-Specification/issues/396#issuecomment-894718960) and [here's yet another](https://github.com/OAI/OpenAPI-Specification/issues/396#issuecomment-1110789391).

I'm not part of the OpenAPI project, but I have led the development of multiple open source projects, and being very involved in several specification style projects like this. Looking over this issue, honestly, there's not a lot of serious interest in it. It takes you 2 minutes to write a comment saying you want this feature. That's not serious interest. Serious interest means submitting serious proposals, attending meetings where you sell those proposals, talking to multiple stakeholders in the project to understand what the different concerns are and addressing that. No one's doing that.

The OpenAPI spec we have today has been built off the backs of that kind of engagement for a decade. It's hard work, working with many different stakeholders all having their different opinions, going back and forth, coming up with solutions, reworking, reworking, reworking, incorporating lots of different feedback. And the result is that we have a quality spec that we all benefit from. People commenting on an issue saying this feature is important, that's just noise. People just turning up to one call and stating their pet feature, that's just noise to. This kind of half-hearted engagement happens a lot, but helps nothing. That's probably why the maintainers have closed this issue. Unless there's someone out there that is willing to do the work of leading this feature and getting it into the spec, no one can claim that it's important enough to be in the spec.

**Comment by hasufell** [comment] 2023-10-04 03:46
@jroper I'm maintaining popular open source projects as well. I know how things work. There was **no call for help** here.

A call for help is when maintainers say "yeah, great idea, we need your help" or "important topic, let's discuss this asap".

As a maintainer, it's easy to get burned out and dismissive, because people are mostly just complaining. But you have to understand that you're hoping for someone else to potentially dedicate their free time to your project.

Small things can make a difference here. E.g. the issue has not beey reopened. That in itself is a signal to potential contributors, whether that was intended or not.

**Comment by jroper** [comment] 2023-10-04 04:04
Disagree. The maintainers have yet to be convinced of the importance of this issue, that's very clear from the comments they've made. They're not hoping for anyone to dedicate their free time to do this because they don't think it's important enough. But they have invited us to convince them otherwise. The fact that no one has done the work to show that has given them their answer. Until someone does, I don't see why they would reopen the issue.

**Comment by hasufell** [comment] 2023-10-04 04:14
@jroper then don't be surprised when people express their frustration due to the lack of interest and engagement of the maintainers.

I'm maintaining a spec myself. And I encourage contributors to write even radical proposals, while being very upfront with the expectations: most of them will likely not be accepted. But it's good to have them anyway.

At any rate, I think most of us here lost interest in contributing.

**Comment by philsturgeon** [comment] 2023-10-04 14:43
As I’ve said several times in this thread (but it’s been hurried under lots of long replies), if you’re interested in this topic please join a weekly call and take the lead on making it happen.

I’m not really involved right now, busy running a climate charity unpaid, but as far as I know there’s nobody on the OpenAPI team who’s being paid to work on things you want. You can work on things you want, if you want.

Alternatively I am available for hire. If you’d like to put me on a retainer I can pioneer efforts to get this change discussed. My rate is $200/hr. 

Otherwise it’s on you. Good luck!

**Comment by olawalejuwonm** [comment] 2024-02-21 09:08
Is there any resolution as regards this? Will AsyncAPI be combined to OpenAPI so we can have server side event documented with it?

**Comment by nikojpapa** [comment] 2024-02-21 22:58
Here is an example of a way I did it back in 2020. This was based off of v4.3.1. I don't remember exactly what I did, so I just remade, in a new repo, the relevant changes to the files that I think were pertinent. I think there is a similar structure in the latest version, so this can likely be adapted as needed.

This is using the new SSE in the typescript-fetch language, but you can change the mustache file that is relevant to you.

https://github.com/nikojpapa/openapi-generator/compare/003165c2c2..03081c9

**Comment by ihakh** [comment] 2024-02-24 07:23
I used it to update the live chart
so in my case the data has a fix structure and api can promise to have a fix structure

**Comment by dsinghvi** [comment] 2024-09-15 18:17
For folks stumbling on this issue, Fern supports server sent events via extensions (https://buildwithfern.com/learn/api-definition/openapi/endpoints/sse)

**Comment by olawalejuwonm** [comment] 2024-09-15 18:47
How can I use it for testing websocket / documenting it

**Comment by megretson** [comment] 2024-10-10 16:14
Hi all,

This issue clearly became contentious based on the above thread, but I was wondering if someone could provide a current status on SSE tooling support? Is there some canonical way of describing SSE or plans to support SSE in the generators? 

Thanks!

**Comment by EwenQuim** [comment] 2024-12-14 14:22
> Here is an example of a way I did it back in 2020. This was based off of v4.3.1. I don't remember exactly what I did, so I just remade, in a new repo, the relevant changes to the files that I think were pertinent. I think there is a similar structure in the latest version, so this can likely be adapted as needed.
> 
> This is using the new SSE in the typescript-fetch language, but you can change the mustache file that is relevant to you.
> 
> https://github.com/nikojpapa/openapi-generator/compare/003165c2c2..03081c9
> 
> You would then set the response in the API definition as something like the following:
> 
>       responses:
>         "200":
>           description: success
>           content:
>             text/event-stream:
>               schema:
>                 $ref: "..."

Same. That's what we use in my client's company for a year or so. I still don't know if it is part of the official spec but it has been ours. 

This way of doing things is already compatible server-side with generators like [Fuego](https://github.com/go-fuego/fuego). But from a client point of view (we use [Orval](https://github.com/anymaniax/orval)), it does not work really well. I think we should add some kind of field in the Response object.

**Comment by handrews** [comment] 2024-12-18 17:02
Please discuss SSE at the open discussion #4171.  I'm going to lock this issue because it's confusing to have ongoing discussion in a long-closed and long-outdated issue.
