### ISSUE TITLE
Pbm try-it function can't display

### ISSUE THREAD

**Issue by rocchisanijl** [OAI/OpenAPI-Specification#1326] opened 2017-08-19 15:53 UTC
hello  (openAPI 3.0.0)
I'm not expert in swagger but i can't understand why try-it button is not displayed in my case.
please find the Yaml file here: [https://pastebin.com/raw/gXetGj1Z]

in swagger 2.0 it worked so???

thanks for help.

best regards.

**Comment by MikeRalphson** [comment] 2017-08-19 16:27
This is still a TODO item, and I believe is expected to arrive during September. See https://github.com/swagger-api/swagger-ui/issues/3338

**Comment by rocchisanijl** [comment] 2017-08-20 15:19
Thanks a lot !!!

**Comment by MikeRalphson** [comment] 2017-09-01 18:17
Dupe of (closed) #1340

**Comment by hkosova** [comment] 2017-09-11 12:01
@rocchisanijl, Swagger UI 3.2.0 now has "try it out" for OpenAPI 3.0.

For future reference, Swagger UI questions should be directed to the [Swagger UI repository](https://github.com/swagger-api/swagger-ui) or the [Google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket). This repository is for the OpenAPI Specification itself and does not cover the Swagger tools.

**Comment by webron** [comment] 2017-09-11 12:16
Thanks everyone. Closing as really not the right repo.

**Closed by webron** 2017-09-11 12:16 UTC
