### ISSUE TITLE
Question: Validation of schema with oneOf when there are no required properties

### ISSUE THREAD

**Issue by pawelusfr** [OAI/OpenAPI-Specification#2202] opened 2020-04-10 06:34 UTC
Considering the schema below:
```yaml
info:
  title: Test
  version: 1.0.0
  description: 'Test'
openapi: 3.0.4
paths:
  '/test':
    patch:
      summary: Test
      description: Validation test
      tags:
       - test
      operationId: test
      requestBody:
        description: Some data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestThis'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
components:
  schemas:
    TestThisOne:
      type: object
      properties:
        title:
          type: string
        refs:
          type: string
          nullable: true
    TestThisTwo:
      type: object
      properties:
        something:
          type: string
    TestThis:
      oneOf:
        - $ref: '#/components/schemas/TestThisOne'
        - $ref: '#/components/schemas/TestThisTwo'
tags:
  - name: test
    description: Test
```
`TestThisOne` and `TestThisTwo` have no required properties so an empty object matches both.

Should following request bodies be allowed by a validator?
```json
{
  "title": "Something"
}
```
```json
{
  "title": "Something",
  "refs": "Some ref"
}
```
```json
{
  "something": "Something"
}
```
Technically they fulfil both `TestThisOne` and `TestThisTwo` schemas as they only contain properties from one and also match an empty object with additional properties (as `additionalProperties` is `true` by default) from the other.

If this should not pass validation then it might be worth mentioning it in the spec as the examples of `oneOf` in the spec do not have required properties so they won't pass validation.

**Comment by LasneF** [comment] 2024-01-25 10:30
this question is more a JsonSchema topic , still 
here is my 2 cents. 
in your 3 sample the validation should fail 

why ? 
because oneOf requires an exclusive choice , and in fact here your schema is by design not 'different' enought 
and here all your data match the 2 schema ( as there is no required properties neither additionalProperties set to false) 

to be efficient  , oneOf should be used in conjonction of criteria that can differentiate the input (can be leveraging additionalProperties , can be leveraging required statement , can be leveraging constrains such as pattern , can be  something else :) 

you can read the good paper from @Relequestual  around it here 
https://json-schema.org/blog/posts/applicability-json-schema-fundamentals-part-1#putting-everything-together-avoiding-oneof-pitfalls

@handrews , @MikeRalphson  this ticket should be closed .

https://json-schema.org/blog/posts/applicability-json-schema-fundamentals-part-1#putting-everything-together-avoiding-oneof-pitfalls

**Comment by handrews** [comment] 2024-01-27 02:32
Thanks @LasneF , closing.

**Closed by handrews** 2024-01-27 02:32 UTC
