### ISSUE TITLE
Question: Create Links from "complex" headers

### ISSUE THREAD

**Issue by meastp** [OAI/OpenAPI-Specification#2402] opened 2020-11-06 06:11 UTC
I'm using the HTTP `Link` header for pagination in my API.

e.g. `GET /items?limit=10&filter=active`

returns a `Link`-header with `Link: <https://example.com/features?limit=10&filter=active&cursor=a34Dsdf>; rel="next"`

What I would like is for the auto-generation tools to be able to create a method e.g. "getNextPortion" that uses the parameters from the Link header to get the next n items.

Is this possible, or must I use "primitive" headers containing single integers and strings?

**Comment by MikeRalphson** [comment] 2020-11-06 09:27
Note: worth keeping an eye on the progress of the [structured fields draft](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html) on its path to becoming an RFC.

**Comment by handrews** [comment] 2024-11-21 21:42
This is a duplicate of #667 which has more info, so I'm closing this in favor of that.

**Closed by handrews** 2024-11-21 21:42 UTC
Labels: links, headers
